# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "geerlingguy/centos7"
    config.vm.network :forwarded_port, guest: 27017, host: 27017
    config.vm.provision "file", source: "config/mongod.conf", destination: "~/mongod.conf"
    config.vm.provision "file", source: "config/mongodb-org-3.6.repo", destination: "~/mongodb-org-3.6.repo"
    config.vm.provision :shell, :path => "install.sh"
    config.vm.synced_folder "./home", "/vagrant", :mount_options => ["dmode=777", "fmode=666"]
end