# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "geerlingguy/centos7"
    config.vm.network :forwarded_port, guest: 3306, host: 3306
    config.vm.provision :shell, :path => "install.sh"
    config.vm.provision "file", source: "config/my.cnf", destination: "~/my.cnf"
    # User must do the database setup manually
    # config.vm.provision "file", source: "config/db-setup.sql", destination: "~/db-setup.sql"
    # config.vm.provision :shell, :path => "setup-mysql-server.sh", privileged: false
    config.vm.synced_folder "./home", "/vagrant", :mount_options => ["dmode=777", "fmode=666"]
end